// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TrabTerceiro.Data
{
    public partial class Categoria
    {
        public Categoria()
        {
            Produto = new HashSet<Produto>();
        }

        [Key]
        [Column("Cat_ID")]
        public int CatId { get; set; }
        [Required]
        [Column("Cat_Nome")]
        [Display(Name ="Categoria")]
        [StringLength(50)]
        public string CatNome { get; set; }

        [InverseProperty("ProCategoriaNavigation")]
        public virtual ICollection<Produto> Produto { get; set; }
    }
}