// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TrabTerceiro.Data
{
    public partial class Cliente
    {
        public Cliente()
        {
            Venda = new HashSet<Venda>();
        }

        [Key]
        [Display(Name = "Cliente")]
        [Column("Cli_ID")]
        public int CliId { get; set; }
        [Required]
        [Display(Name = "Cliente")]
        [Column("Cli_Nome")]
        [StringLength(50)]
        public string CliNome { get; set; }
        [Required]
        [Display(Name = "Email")]
        [Column("Cli_Email")]
        [StringLength(50)]
        public string CliEmail { get; set; }
        [Required]
        [Display(Name = "CPF")]
        [Column("Cli_CPF")]
        [StringLength(50)]
        public string CliCpf { get; set; }

        [InverseProperty("IdCliNavigation")]
        [Display(Name = "Cliente")]
        public virtual ICollection<Venda> Venda { get; set; }
    }
}