// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TrabTerceiro.Data
{
    public partial class Produto
    {
        public Produto()
        {
            VendaProduto = new HashSet<VendaProduto>();
        }

        [Key]
        [Column("Pro_ID")]
        [Display(Name = "Produto")]
        public int ProId { get; set; }
        [Required]
        [Display(Name = "Produto")]
        [Column("Pro_Nome")]
        [StringLength(50)]
        public string ProNome { get; set; }
        [Column("Pro_Categoria")]
        [Display(Name = "Categoria")]
        public int ProCategoria { get; set; }
        [Column("Pro_Fornecedor")]
        [Display(Name = "Fornecedor")]
        public int ProFornecedor { get; set; }
        [Column("Pro_Preco", TypeName = "money")]
        [Display(Name = "Preço")]
        public decimal ProPreco { get; set; }

        [ForeignKey(nameof(ProCategoria))]
        [InverseProperty(nameof(Categoria.Produto))]
        [Display(Name = "Categoria")]
        public virtual Categoria ProCategoriaNavigation { get; set; }
        [ForeignKey(nameof(ProFornecedor))]
        [InverseProperty(nameof(Fornecedor.Produto))]
        [Display(Name = "Fornecedor")]
        public virtual Fornecedor ProFornecedorNavigation { get; set; }
        [InverseProperty("IdProdutoNavigation")]
        [Display(Name = "Produto")]
        public virtual ICollection<VendaProduto> VendaProduto { get; set; }
    }
}