// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TrabTerceiro.Data
{
    public partial class Venda
    {
        public Venda()
        {
            VendaProduto = new HashSet<VendaProduto>();
        }

        [Key]
        [Column("Ven_ID")]
        public int VenId { get; set; }
        [Column("ID_Cli")]
        [Display(Name = "Cliente")]
        public int IdCli { get; set; }
        [Column("Ven_Data", TypeName = "date")]
        [Display(Name = "Data")]
        public DateTime VenData { get; set; }
        [Column("Ven_Fechada")]
        [Display(Name = "Venda Fechada")]
        public bool VenFechada { get; set; }

        [ForeignKey(nameof(IdCli))]
        [InverseProperty(nameof(Cliente.Venda))]
        [Display(Name = "Cliente")]
        public virtual Cliente IdCliNavigation { get; set; }
        [InverseProperty("IdVendaNavigation")]
        public virtual ICollection<VendaProduto> VendaProduto { get; set; }
    }
}