// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TrabTerceiro.Data
{
    public partial class VendaProduto
    {
        [Key]
        [Column("VeP_ID")]
        public int VePId { get; set; }
        [Column("ID_Venda")]
        public int IdVenda { get; set; }
        [Column("ID_Produto")]
        [Display(Name = "Produto")]
        public int IdProduto { get; set; }
        [Column("VeP_Qtd")]
        [Display(Name = "Quantidade")]
        public int VePQtd { get; set; }
        [Column("VeP_PrecoVenda", TypeName = "money")]
        [Display(Name = "Preço de Venda")]
        public decimal VePPrecoVenda { get; set; }

        [ForeignKey(nameof(IdProduto))]
        [InverseProperty(nameof(Produto.VendaProduto))]
        [Display(Name = "Produto")]
        public virtual Produto IdProdutoNavigation { get; set; }
        [ForeignKey(nameof(IdVenda))]
        [InverseProperty(nameof(Venda.VendaProduto))]
        public virtual Venda IdVendaNavigation { get; set; }
    }
}